export const alphabet = [
  { key: "a", picked: false, status: false },
  { key: "b", picked: false, status: false },
  { key: "c", picked: false, status: false },
  { key: "d", picked: false, status: false },
  { key: "e", picked: false, status: false },
  { key: "f", picked: false, status: false },
  { key: "g", picked: false, status: false },
  { key: "h", picked: false, status: false },
  { key: "i", picked: false, status: false },
  { key: "j", picked: false, status: false },
  { key: "k", picked: false, status: false },
  { key: "l", picked: false, status: false },
  { key: "m", picked: false, status: false },
  { key: "n", picked: false, status: false },
  { key: "o", picked: false, status: false },
  { key: "p", picked: false, status: false },
  { key: "q", picked: false, status: false },
  { key: "r", picked: false, status: false },
  { key: "s", picked: false, status: false },
  { key: "t", picked: false, status: false },
  { key: "u", picked: false, status: false },
  { key: "v", picked: false, status: false },
  { key: "x", picked: false, status: false },
  { key: "w", picked: false, status: false },
  { key: "y", picked: false, status: false },
  { key: "z", picked: false, status: false },
];

export default alphabet;
